#Tecla SUPER
$mainMod = SUPER

#Teclado + Mouse
input {
    kb_layout = br
    kb_variant = 
    follow_mouse = 0
}
cursor {
    no_hardware_cursors = true
}

# Inicialização
exec-once = swww-daemon --no-cache
exec-once = waybar

#Monitores 
monitor = DP-1, 1920x1080@165, 0x0, 1

# Variáveis de Ambiente NVIDIA 
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct

#Animações
animations {
    enabled = yes
    animation = workspaces, 1, 3, default, slide
}

#BINDS

	# --- Abrir apps ---
bind = CTRL, T, exec, ghostty
bind = $mainMod, Q, killactive
bind = $mainMod, B, exec, zen-browser
bind = $mainMod, RETURN, exec, rofi -show drun
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy
bind = ALT, Tab, exec, rofi -show window
bind = $mainMod, M, togglespecialworkspace, magic
bind = $mainMod SHIFT, M, movetoworkspace, special:magic

	# --- Controlo de Volume ---
binde = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 1%+
binde = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-
bind  = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioPlay, exec, playerctl play-pause

	# --- Trocar de Workspace (1-5) ---
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

	# --- Mudar o foco das janelas ---
bind = ALT, left, movefocus, l
bind = ALT, right, movefocus, r
bind = ALT, up, movefocus, u
bind = ALT, down, movefocus, d

	# --- Mover a janela ativa para um Workspace ---
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

	# --- Mover a janela ativa para um Workspace com setinha ---
bind = $mainMod SHIFT, right, movetoworkspace, +1
bind = $mainMod SHIFT, left, movetoworkspace, -1

	# --- Mudar de workspace com setinhas ---
bind = $mainMod, right, workspace, +1
bind = $mainMod, left, workspace, -1
