

# 1. Configurações de Monitores
source = ~/.config/hypr/monitors.conf

# 2. Programas e Autostart (Waybar, Hyprpaper/Swaybg, Dunst/Mako, Pipewire)
source = ~/.config/hypr/autostart.conf

# 3. Variáveis de Ambiente (Nvidia, QT, GTK)
source = ~/.config/hypr/env.conf

# 4. Input, Animações e Decorações
source = ~/.config/hypr/look_and_feel.conf

# 5. Keybindings e Regras de Janela
source = ~/.config/hypr/keybinds.conf

