#Tecla SUPER
$mainMod = SUPER

#Teclado + Mouse
input {
    kb_layout = br
    kb_variant = 
    follow_mouse = 0
}
cursor {
    no_hardware_cursors = true
}

#BINDS

	# --- Abrir apps ---
bind = $mainMod, T, exec, ghostty
bind = $mainMod, Q, killactive
bind = $mainMod, B, exec, zen-browser
bind = $mainMod, RETURN, exec, rofi -show drun
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy
bind = ALT, Tab, exec, rofi -show window
bind = $mainMod, M, togglespecialworkspace, magic
bind = $mainMod SHIFT, M, movetoworkspace, special:magic

	# --- Controlo de Mídia ---
binde = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 1%+
binde = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-
bind  = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = , XF86AudioNext, exec, playerctl next


	# --- Trocar de Workspace (1-5) ---
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

	# --- Mover a janela ativa para um Workspace ---
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

	# --- Mover a janela ativa para um Workspace com setinha ---
bind = $mainMod SHIFT, right, movetoworkspace, +1
bind = $mainMod SHIFT, left, movetoworkspace, -1

	# --- Mudar de workspace com setinhas ---
bind = $mainMod, right, workspace, +1
bind = $mainMod, left, workspace, -1
